### ISSUE TITLE
This library does not work in OpenModelica

### ISSUE THREAD

**Issue by dady6882** [modelica-3rdparty/WasteWater#1]
Please, does someone know how can I get this WW library work in Openmodelica??

**Comment by aptok** [comment]
It is possible to run the examples in OMEdit with simulation flags. The model depends on some dymola magic to initialize some parameters: https://trac.openmodelica.org/OpenModelica/ticket/3093#comment:6
https://github.com/modelica-3rdparty/WasteWater/commit/d42eef9
To pass the simulation flag to OMEdit you have to fill in 'Additiona Simulation Flags' in the Simulation Setup under 'Simulation Flags' (scroll all the way down).
Be aware of the OpenModelica relative path problem, so either give the absolute path to the file or change the working direcotry in 'Menu 'Tools -> General' to the WasteWater directory.
You have also to prepare override files for your own models.
