### ISSUE TITLE
Lack of Exe files 

### ISSUE THREAD

**Issue by amirfard** [modelica-3rdparty/WasteWater#5]
Hi. None of ASM1, ASM2 and ASM3 has any Exe files? There are just some codes' files.

Regards,
Amir

**Comment by dietmarw** [comment]
There are no exe files because WasteWater is not a program but a Modelica library. In order to use it you need a [Modelica tool](https://modelica.org/tools). The free and open source tool [OpenModelica](https://openmodelica.org) even packages that library as far as I know.
