### ISSUE TITLE
Is there a pssibility to have several release of OpenModelica on a computer?

### ISSUE THREAD

**Issue by jph-tavella** [modelica-3rdparty/WasteWater#8]
Is there a possibility to keep several releases of OpenModelica on a computer?
Could be interesting to compare results or behaviors to more easily see regressions.

**Comment by dietmarw** [comment]
Sorry, this is the issue tracker for the WasteWater library and not the OpenModelica tool. Also you don't seem to want to report an issue but rather have a question. I suggest you ask your question here: https://stackoverflow.com/questions/tagged/openmodelica

**Comment by jph-tavella** [comment]
sorry yes please cancel my wrong request
